/**
 * The illustrated icon set.
 *
 * One sheet, fifteen icons, drawn as a CSS sprite: a single request, and it
 * caches with the rest of the app.
 *
 * The sheet is generated by `tools/build-brand-icons.cjs`, which cuts the black
 * background out of the original artwork, measures each icon to the pixel and
 * lays them out on an even grid — so the maths here is a multiplication and
 * nothing can end up cropped. The names below are the captions printed under
 * each icon on the original sheet, in the same reading order.
 */

import type { CSSProperties, ReactElement } from 'react';

const SHEET = './brand-icons.png';
/** Must match the constants in the build script. */
const CELL = 144;
const COLUMNS = 5;
const ROWS = 3;

export type BrandIconName =
  | 'agenda' | 'treinos' | 'corrida' | 'bicicleta' | 'alimentacao'
  | 'progresso' | 'objetivos' | 'hidratacao' | 'ia' | 'lembretes'
  | 'sono' | 'perfil' | 'saude' | 'relaxamento' | 'estatisticas';

const ORDER: BrandIconName[] = [
  'agenda', 'treinos', 'corrida', 'bicicleta', 'alimentacao',
  'progresso', 'objetivos', 'hidratacao', 'ia', 'lembretes',
  'sono', 'perfil', 'saude', 'relaxamento', 'estatisticas',
];

function spriteStyle(name: BrandIconName, size: number): CSSProperties {
  const index = Math.max(0, ORDER.indexOf(name));
  const column = index % COLUMNS;
  const row = Math.floor(index / COLUMNS);
  const scale = size / CELL;

  return {
    width: size,
    height: size,
    backgroundImage: `url(${SHEET})`,
    backgroundSize: `${CELL * COLUMNS * scale}px ${CELL * ROWS * scale}px`,
    backgroundPosition: `${-column * size}px ${-row * size}px`,
    backgroundRepeat: 'no-repeat',
  };
}

export function BrandIcon({
  name, size = 44, float, label,
}: {
  name: BrandIconName;
  size?: number;
  /** A slow idle drift, for the few places an icon is the hero. */
  float?: boolean;
  label?: string;
}): ReactElement {
  return (
    <span
      className={`brand-icon${float ? ' is-floating' : ''}`}
      style={spriteStyle(name, size)}
      role={label ? 'img' : 'presentation'}
      aria-label={label}
      aria-hidden={label ? undefined : true}
    />
  );
}

/**
 * The icon on a soft disc.
 *
 * Now that the artwork has no background of its own, the disc is optional —
 * it exists to give an icon presence where it sits alone in a row.
 */
export function BrandIconTile({
  name, size = 44, float, label,
}: {
  name: BrandIconName;
  size?: number;
  float?: boolean;
  label?: string;
}): ReactElement {
  return (
    <span className="brand-tile" style={{ width: size * 1.5, height: size * 1.5 }}>
      <BrandIcon name={name} size={size} float={float} label={label} />
    </span>
  );
}
